# Generated by Django 3.2.9 on 2022-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_auto_20220531_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.CharField(default='Some Description', max_length=500),
        ),
    ]
