# Generated by Django 3.2.9 on 2022-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0003_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(default='Some Description', max_length=5000),
        ),
    ]
